SELECT D.SURNAME, D.NAME, D.ESTABLISHED_POST AS POST, D.DATE_OF_BIRTH, A.*, COUNT(*) AS 'NUMBER OF CARS' FROM DRIVERS D LEFT JOIN ADDRESSES A ON A.ID=D.ADDRESSES_ID
LEFT JOIN DRIVER_HAS_DRIVERS_CARS DHDC ON DHDC.DRIVER_ID=D.ID LEFT JOIN DRIVERS_CARS DC ON DC.ID=DHDC.DRIVERS_CARS_ID WHERE D.SURNAME LIKE 'E%' ORDER BY D.SURNAME ASC;
