USE MYDB;
SELECT COUNT(DC.CAR_MODEL) AS 'CARS NUMBER GROUP BY MODELS', DC.CAR_MODEL, D.NAME, D.SURNAME FROM DRIVERS D INNER JOIN ADDRESSES A ON D.ADDRESSES_ID = A.ID 
INNER JOIN DRIVERS_CARS DC ON D.ID = DC.ID GROUP BY CAR_MODEL HAVING D.SURNAME = 'Ivanoff';